// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/goodsetting"
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/predicate"
)

// GoodSettingDelete is the builder for deleting a GoodSetting entity.
type GoodSettingDelete struct {
	config
	hooks    []Hook
	mutation *GoodSettingMutation
}

// Where appends a list predicates to the GoodSettingDelete builder.
func (gsd *GoodSettingDelete) Where(ps ...predicate.GoodSetting) *GoodSettingDelete {
	gsd.mutation.Where(ps...)
	return gsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gsd *GoodSettingDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gsd.hooks) == 0 {
		affected, err = gsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GoodSettingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gsd.mutation = mutation
			affected, err = gsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gsd.hooks) - 1; i >= 0; i-- {
			if gsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gsd *GoodSettingDelete) ExecX(ctx context.Context) int {
	n, err := gsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gsd *GoodSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: goodsetting.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: goodsetting.FieldID,
			},
		},
	}
	if ps := gsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, gsd.driver, _spec)
}

// GoodSettingDeleteOne is the builder for deleting a single GoodSetting entity.
type GoodSettingDeleteOne struct {
	gsd *GoodSettingDelete
}

// Exec executes the deletion query.
func (gsdo *GoodSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := gsdo.gsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{goodsetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gsdo *GoodSettingDeleteOne) ExecX(ctx context.Context) {
	gsdo.gsd.ExecX(ctx)
}
