// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/platformbenefit"
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/predicate"
)

// PlatformBenefitDelete is the builder for deleting a PlatformBenefit entity.
type PlatformBenefitDelete struct {
	config
	hooks    []Hook
	mutation *PlatformBenefitMutation
}

// Where appends a list predicates to the PlatformBenefitDelete builder.
func (pbd *PlatformBenefitDelete) Where(ps ...predicate.PlatformBenefit) *PlatformBenefitDelete {
	pbd.mutation.Where(ps...)
	return pbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pbd *PlatformBenefitDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pbd.hooks) == 0 {
		affected, err = pbd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PlatformBenefitMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pbd.mutation = mutation
			affected, err = pbd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pbd.hooks) - 1; i >= 0; i-- {
			if pbd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pbd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pbd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pbd *PlatformBenefitDelete) ExecX(ctx context.Context) int {
	n, err := pbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pbd *PlatformBenefitDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: platformbenefit.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: platformbenefit.FieldID,
			},
		},
	}
	if ps := pbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pbd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// PlatformBenefitDeleteOne is the builder for deleting a single PlatformBenefit entity.
type PlatformBenefitDeleteOne struct {
	pbd *PlatformBenefitDelete
}

// Exec executes the deletion query.
func (pbdo *PlatformBenefitDeleteOne) Exec(ctx context.Context) error {
	n, err := pbdo.pbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{platformbenefit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pbdo *PlatformBenefitDeleteOne) ExecX(ctx context.Context) {
	pbdo.pbd.ExecX(ctx)
}
