// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/coinaccountinfo"
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/coinaccounttransaction"
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	coinaccountinfoFields := schema.CoinAccountInfo{}.Fields()
	_ = coinaccountinfoFields
	// coinaccountinfoDescCreateAt is the schema descriptor for create_at field.
	coinaccountinfoDescCreateAt := coinaccountinfoFields[8].Descriptor()
	// coinaccountinfo.DefaultCreateAt holds the default value on creation for the create_at field.
	coinaccountinfo.DefaultCreateAt = coinaccountinfoDescCreateAt.Default.(func() uint32)
	// coinaccountinfoDescUpdateAt is the schema descriptor for update_at field.
	coinaccountinfoDescUpdateAt := coinaccountinfoFields[9].Descriptor()
	// coinaccountinfo.DefaultUpdateAt holds the default value on creation for the update_at field.
	coinaccountinfo.DefaultUpdateAt = coinaccountinfoDescUpdateAt.Default.(func() uint32)
	// coinaccountinfo.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	coinaccountinfo.UpdateDefaultUpdateAt = coinaccountinfoDescUpdateAt.UpdateDefault.(func() uint32)
	// coinaccountinfoDescDeleteAt is the schema descriptor for delete_at field.
	coinaccountinfoDescDeleteAt := coinaccountinfoFields[10].Descriptor()
	// coinaccountinfo.DefaultDeleteAt holds the default value on creation for the delete_at field.
	coinaccountinfo.DefaultDeleteAt = coinaccountinfoDescDeleteAt.Default.(func() uint32)
	// coinaccountinfoDescID is the schema descriptor for id field.
	coinaccountinfoDescID := coinaccountinfoFields[0].Descriptor()
	// coinaccountinfo.DefaultID holds the default value on creation for the id field.
	coinaccountinfo.DefaultID = coinaccountinfoDescID.Default.(func() uuid.UUID)
	coinaccounttransactionFields := schema.CoinAccountTransaction{}.Fields()
	_ = coinaccounttransactionFields
	// coinaccounttransactionDescCreateAt is the schema descriptor for create_at field.
	coinaccounttransactionDescCreateAt := coinaccounttransactionFields[11].Descriptor()
	// coinaccounttransaction.DefaultCreateAt holds the default value on creation for the create_at field.
	coinaccounttransaction.DefaultCreateAt = coinaccounttransactionDescCreateAt.Default.(func() uint32)
	// coinaccounttransactionDescUpdateAt is the schema descriptor for update_at field.
	coinaccounttransactionDescUpdateAt := coinaccounttransactionFields[12].Descriptor()
	// coinaccounttransaction.DefaultUpdateAt holds the default value on creation for the update_at field.
	coinaccounttransaction.DefaultUpdateAt = coinaccounttransactionDescUpdateAt.Default.(func() uint32)
	// coinaccounttransaction.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	coinaccounttransaction.UpdateDefaultUpdateAt = coinaccounttransactionDescUpdateAt.UpdateDefault.(func() uint32)
	// coinaccounttransactionDescDeleteAt is the schema descriptor for delete_at field.
	coinaccounttransactionDescDeleteAt := coinaccounttransactionFields[13].Descriptor()
	// coinaccounttransaction.DefaultDeleteAt holds the default value on creation for the delete_at field.
	coinaccounttransaction.DefaultDeleteAt = coinaccounttransactionDescDeleteAt.Default.(func() uint32)
	// coinaccounttransactionDescID is the schema descriptor for id field.
	coinaccounttransactionDescID := coinaccounttransactionFields[0].Descriptor()
	// coinaccounttransaction.DefaultID holds the default value on creation for the id field.
	coinaccounttransaction.DefaultID = coinaccounttransactionDescID.Default.(func() uuid.UUID)
}
