// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/userpaymentbalance"
)

// UserPaymentBalanceDelete is the builder for deleting a UserPaymentBalance entity.
type UserPaymentBalanceDelete struct {
	config
	hooks    []Hook
	mutation *UserPaymentBalanceMutation
}

// Where appends a list predicates to the UserPaymentBalanceDelete builder.
func (upbd *UserPaymentBalanceDelete) Where(ps ...predicate.UserPaymentBalance) *UserPaymentBalanceDelete {
	upbd.mutation.Where(ps...)
	return upbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (upbd *UserPaymentBalanceDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(upbd.hooks) == 0 {
		affected, err = upbd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserPaymentBalanceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			upbd.mutation = mutation
			affected, err = upbd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(upbd.hooks) - 1; i >= 0; i-- {
			if upbd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = upbd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, upbd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (upbd *UserPaymentBalanceDelete) ExecX(ctx context.Context) int {
	n, err := upbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (upbd *UserPaymentBalanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userpaymentbalance.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userpaymentbalance.FieldID,
			},
		},
	}
	if ps := upbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, upbd.driver, _spec)
}

// UserPaymentBalanceDeleteOne is the builder for deleting a single UserPaymentBalance entity.
type UserPaymentBalanceDeleteOne struct {
	upbd *UserPaymentBalanceDelete
}

// Exec executes the deletion query.
func (upbdo *UserPaymentBalanceDeleteOne) Exec(ctx context.Context) error {
	n, err := upbdo.upbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userpaymentbalance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (upbdo *UserPaymentBalanceDeleteOne) ExecX(ctx context.Context) {
	upbdo.upbd.ExecX(ctx)
}
