// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/cloud-hashing-billing/pkg/db/ent/userbenefit"
	"github.com/google/uuid"
)

// UserBenefitQuery is the builder for querying UserBenefit entities.
type UserBenefitQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserBenefit
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserBenefitQuery builder.
func (ubq *UserBenefitQuery) Where(ps ...predicate.UserBenefit) *UserBenefitQuery {
	ubq.predicates = append(ubq.predicates, ps...)
	return ubq
}

// Limit adds a limit step to the query.
func (ubq *UserBenefitQuery) Limit(limit int) *UserBenefitQuery {
	ubq.limit = &limit
	return ubq
}

// Offset adds an offset step to the query.
func (ubq *UserBenefitQuery) Offset(offset int) *UserBenefitQuery {
	ubq.offset = &offset
	return ubq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ubq *UserBenefitQuery) Unique(unique bool) *UserBenefitQuery {
	ubq.unique = &unique
	return ubq
}

// Order adds an order step to the query.
func (ubq *UserBenefitQuery) Order(o ...OrderFunc) *UserBenefitQuery {
	ubq.order = append(ubq.order, o...)
	return ubq
}

// First returns the first UserBenefit entity from the query.
// Returns a *NotFoundError when no UserBenefit was found.
func (ubq *UserBenefitQuery) First(ctx context.Context) (*UserBenefit, error) {
	nodes, err := ubq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userbenefit.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ubq *UserBenefitQuery) FirstX(ctx context.Context) *UserBenefit {
	node, err := ubq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserBenefit ID from the query.
// Returns a *NotFoundError when no UserBenefit ID was found.
func (ubq *UserBenefitQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ubq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userbenefit.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ubq *UserBenefitQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ubq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserBenefit entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserBenefit entity is found.
// Returns a *NotFoundError when no UserBenefit entities are found.
func (ubq *UserBenefitQuery) Only(ctx context.Context) (*UserBenefit, error) {
	nodes, err := ubq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userbenefit.Label}
	default:
		return nil, &NotSingularError{userbenefit.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ubq *UserBenefitQuery) OnlyX(ctx context.Context) *UserBenefit {
	node, err := ubq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserBenefit ID in the query.
// Returns a *NotSingularError when more than one UserBenefit ID is found.
// Returns a *NotFoundError when no entities are found.
func (ubq *UserBenefitQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ubq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userbenefit.Label}
	default:
		err = &NotSingularError{userbenefit.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ubq *UserBenefitQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ubq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserBenefits.
func (ubq *UserBenefitQuery) All(ctx context.Context) ([]*UserBenefit, error) {
	if err := ubq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ubq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ubq *UserBenefitQuery) AllX(ctx context.Context) []*UserBenefit {
	nodes, err := ubq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserBenefit IDs.
func (ubq *UserBenefitQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := ubq.Select(userbenefit.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ubq *UserBenefitQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ubq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ubq *UserBenefitQuery) Count(ctx context.Context) (int, error) {
	if err := ubq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ubq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ubq *UserBenefitQuery) CountX(ctx context.Context) int {
	count, err := ubq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ubq *UserBenefitQuery) Exist(ctx context.Context) (bool, error) {
	if err := ubq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ubq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ubq *UserBenefitQuery) ExistX(ctx context.Context) bool {
	exist, err := ubq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserBenefitQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ubq *UserBenefitQuery) Clone() *UserBenefitQuery {
	if ubq == nil {
		return nil
	}
	return &UserBenefitQuery{
		config:     ubq.config,
		limit:      ubq.limit,
		offset:     ubq.offset,
		order:      append([]OrderFunc{}, ubq.order...),
		predicates: append([]predicate.UserBenefit{}, ubq.predicates...),
		// clone intermediate query.
		sql:    ubq.sql.Clone(),
		path:   ubq.path,
		unique: ubq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserBenefit.Query().
//		GroupBy(userbenefit.FieldAppID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ubq *UserBenefitQuery) GroupBy(field string, fields ...string) *UserBenefitGroupBy {
	group := &UserBenefitGroupBy{config: ubq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ubq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ubq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//	}
//
//	client.UserBenefit.Query().
//		Select(userbenefit.FieldAppID).
//		Scan(ctx, &v)
//
func (ubq *UserBenefitQuery) Select(fields ...string) *UserBenefitSelect {
	ubq.fields = append(ubq.fields, fields...)
	return &UserBenefitSelect{UserBenefitQuery: ubq}
}

func (ubq *UserBenefitQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ubq.fields {
		if !userbenefit.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ubq.path != nil {
		prev, err := ubq.path(ctx)
		if err != nil {
			return err
		}
		ubq.sql = prev
	}
	return nil
}

func (ubq *UserBenefitQuery) sqlAll(ctx context.Context) ([]*UserBenefit, error) {
	var (
		nodes = []*UserBenefit{}
		_spec = ubq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserBenefit{config: ubq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ubq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ubq *UserBenefitQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ubq.querySpec()
	_spec.Node.Columns = ubq.fields
	if len(ubq.fields) > 0 {
		_spec.Unique = ubq.unique != nil && *ubq.unique
	}
	return sqlgraph.CountNodes(ctx, ubq.driver, _spec)
}

func (ubq *UserBenefitQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ubq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ubq *UserBenefitQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userbenefit.Table,
			Columns: userbenefit.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userbenefit.FieldID,
			},
		},
		From:   ubq.sql,
		Unique: true,
	}
	if unique := ubq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ubq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userbenefit.FieldID)
		for i := range fields {
			if fields[i] != userbenefit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ubq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ubq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ubq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ubq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ubq *UserBenefitQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ubq.driver.Dialect())
	t1 := builder.Table(userbenefit.Table)
	columns := ubq.fields
	if len(columns) == 0 {
		columns = userbenefit.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ubq.sql != nil {
		selector = ubq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ubq.unique != nil && *ubq.unique {
		selector.Distinct()
	}
	for _, p := range ubq.predicates {
		p(selector)
	}
	for _, p := range ubq.order {
		p(selector)
	}
	if offset := ubq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ubq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserBenefitGroupBy is the group-by builder for UserBenefit entities.
type UserBenefitGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ubgb *UserBenefitGroupBy) Aggregate(fns ...AggregateFunc) *UserBenefitGroupBy {
	ubgb.fns = append(ubgb.fns, fns...)
	return ubgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ubgb *UserBenefitGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ubgb.path(ctx)
	if err != nil {
		return err
	}
	ubgb.sql = query
	return ubgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ubgb *UserBenefitGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ubgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ubgb *UserBenefitGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ubgb.fields) > 1 {
		return nil, errors.New("ent: UserBenefitGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ubgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ubgb *UserBenefitGroupBy) StringsX(ctx context.Context) []string {
	v, err := ubgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ubgb *UserBenefitGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ubgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbenefit.Label}
	default:
		err = fmt.Errorf("ent: UserBenefitGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ubgb *UserBenefitGroupBy) StringX(ctx context.Context) string {
	v, err := ubgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ubgb *UserBenefitGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ubgb.fields) > 1 {
		return nil, errors.New("ent: UserBenefitGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ubgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ubgb *UserBenefitGroupBy) IntsX(ctx context.Context) []int {
	v, err := ubgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ubgb *UserBenefitGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ubgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbenefit.Label}
	default:
		err = fmt.Errorf("ent: UserBenefitGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ubgb *UserBenefitGroupBy) IntX(ctx context.Context) int {
	v, err := ubgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ubgb *UserBenefitGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ubgb.fields) > 1 {
		return nil, errors.New("ent: UserBenefitGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ubgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ubgb *UserBenefitGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ubgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ubgb *UserBenefitGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ubgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbenefit.Label}
	default:
		err = fmt.Errorf("ent: UserBenefitGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ubgb *UserBenefitGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ubgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ubgb *UserBenefitGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ubgb.fields) > 1 {
		return nil, errors.New("ent: UserBenefitGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ubgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ubgb *UserBenefitGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ubgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ubgb *UserBenefitGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ubgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbenefit.Label}
	default:
		err = fmt.Errorf("ent: UserBenefitGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ubgb *UserBenefitGroupBy) BoolX(ctx context.Context) bool {
	v, err := ubgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ubgb *UserBenefitGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ubgb.fields {
		if !userbenefit.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ubgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ubgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ubgb *UserBenefitGroupBy) sqlQuery() *sql.Selector {
	selector := ubgb.sql.Select()
	aggregation := make([]string, 0, len(ubgb.fns))
	for _, fn := range ubgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ubgb.fields)+len(ubgb.fns))
		for _, f := range ubgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ubgb.fields...)...)
}

// UserBenefitSelect is the builder for selecting fields of UserBenefit entities.
type UserBenefitSelect struct {
	*UserBenefitQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ubs *UserBenefitSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ubs.prepareQuery(ctx); err != nil {
		return err
	}
	ubs.sql = ubs.UserBenefitQuery.sqlQuery(ctx)
	return ubs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ubs *UserBenefitSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ubs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ubs *UserBenefitSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ubs.fields) > 1 {
		return nil, errors.New("ent: UserBenefitSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ubs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ubs *UserBenefitSelect) StringsX(ctx context.Context) []string {
	v, err := ubs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ubs *UserBenefitSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ubs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbenefit.Label}
	default:
		err = fmt.Errorf("ent: UserBenefitSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ubs *UserBenefitSelect) StringX(ctx context.Context) string {
	v, err := ubs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ubs *UserBenefitSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ubs.fields) > 1 {
		return nil, errors.New("ent: UserBenefitSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ubs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ubs *UserBenefitSelect) IntsX(ctx context.Context) []int {
	v, err := ubs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ubs *UserBenefitSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ubs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbenefit.Label}
	default:
		err = fmt.Errorf("ent: UserBenefitSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ubs *UserBenefitSelect) IntX(ctx context.Context) int {
	v, err := ubs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ubs *UserBenefitSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ubs.fields) > 1 {
		return nil, errors.New("ent: UserBenefitSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ubs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ubs *UserBenefitSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ubs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ubs *UserBenefitSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ubs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbenefit.Label}
	default:
		err = fmt.Errorf("ent: UserBenefitSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ubs *UserBenefitSelect) Float64X(ctx context.Context) float64 {
	v, err := ubs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ubs *UserBenefitSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ubs.fields) > 1 {
		return nil, errors.New("ent: UserBenefitSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ubs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ubs *UserBenefitSelect) BoolsX(ctx context.Context) []bool {
	v, err := ubs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ubs *UserBenefitSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ubs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbenefit.Label}
	default:
		err = fmt.Errorf("ent: UserBenefitSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ubs *UserBenefitSelect) BoolX(ctx context.Context) bool {
	v, err := ubs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ubs *UserBenefitSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ubs.sql.Query()
	if err := ubs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
